language: go

sudo: false

go:
- 1.14
- 1.15

env:
  - GO111MODULE=on


install:
  - go get -t ./...
  - go get -u github.com/caddyserver/xcaddy/cmd/xcaddy
  - go get github.com/mattn/goveralls

before_script:
  - xcaddy build

script:
  - $GOPATH/bin/goveralls -service=travis-ci
